################################################################################
# Joshua C. Fjelstul, Ph.D.
# evoeu R package
# automatically generated by the codebookr R package
################################################################################

#' Data on links between documents in the acquis communautaire
#' 
#' This dataset includes on observation per edges in the network of European
#' Union legal documents. An edge is a connection between two documents,
#' created by the newer of the two documents. The dataset tracks the following
#' types of connections: "cites all or part of" (most types of documents),
#' "changes text in clause of" (secondary laws), "replaces clause of"
#' (secondary laws), "adds text to clause of" (secondary laws), "inserts new
#' clause in" (secondary laws), "repeals all or part of" (secondary laws),
#' "has legal basis in" (secondary laws), "interprets all or part of"
#' (references for a preliminary ruling), "answers question referred by"
#' (references for a preliminary ruling), "determines compliance with"
#' (actions for failure to fulfill obligations), "upholds all or part of"
#' (case law), "overturns all or part of" (case law), and "transposes all or
#' part of" (national implementing measures).
#' 
#' @format A data frame with 9 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sorting order.}
#' \item{outgoing_celex}{String. The CELEX number of the outgoing document
#' (the document that creates the edge).}
#' \item{outgoing_node_type_id}{Numeric. An ID number that uniquely identifies
#' the type of the outgoing node.}
#' \item{outgoing_node_type}{String. The type of the outgoing node (the
#' document that creates the edge). Possible values include: \code{Treaty
#' articles}, \code{Directives}, \code{Regulations}. \code{Decisions},
#' \code{Court of Justice judgments}, \code{Advocate general opinions},
#' \code{General Court judgments}, \code{National implementing measures}, and
#' \code{National court decisions}.}
#' \item{edge_type_id}{Numeric. An ID number that uniquely identifies the type
#' of the edge.}
#' \item{edge_type}{String. The type of the edge. Possible values include:
#' \code{Cites all or part of}, \code{Changes text in clause of},
#' \code{Replaces clause of}, \code{Adds text to clause of}, \code{Inserts new
#' clause in}, \code{Repeals all or part of}, \code{Has legal basis in},
#' \code{Interprets all or part of}, \code{Answers question referred by},
#' \code{Determines compliance with}, \code{Upholds all or part of},
#' \code{Overturns all or part of}, and\code{Transposes all or part of}.}
#' \item{incoming_celex}{String. The CELEX number of the incoming document
#' (the document that the edge leads to). }
#' \item{incoming_node_type_id}{Numeric. An ID number that uniquely identifies
#' the type of the incoming node.}
#' \item{incoming_node_type}{String. The type of the incoming node (the
#' document that the edge leads to). Possible values include: \code{Treaty
#' articles}, \code{Directives}, \code{Regulations}. \code{Decisions},
#' \code{Court of Justice judgments}, \code{Advocate general opinions},
#' \code{General Court judgments}, \code{National implementing measures}, and
#' \code{National court decisions}.}
#' }
"edges"

################################################################################
# end R script
################################################################################

