################################################################################
# Joshua C. Fjelstul, Ph.D.
# evoeu R package
# automatically generated by the codebookr R package
################################################################################

#' Nodes data
#' 
#' The \code{nodes} dataset includes one one observation per node in the
#' network of European Union legal documents. Each node is a document. This
#' network includes primary law (i.e., treaty articles), secondary law (i.e.,
#' legislation), and case law (i.e., court cases). The dataset incdicates the
#' CELEX number of each document, which is a unique ID number assigned by
#' EUR-Lex, the date of the document, the author of the document, and the type
#' of the document. The dataset includes the following types of documents:
#' treaty articles, directives, regulations, decisions, Court of Justice
#' judgments, advocate general opinions, General Court judgments, national
#' implementing measures (i.e., national legislation that member states enact
#' to transpose EU directives), and national court decisions that apply EU
#' law.
#' 
#' @format A data frame with 9 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation. Indicates the default sorting order.}
#' \item{celex}{String. The CELEX number for the document.}
#' \item{node_type_id}{Numeric. An ID number that uniquely identifies the type
#' of the outgoing node.}
#' \item{node_type}{String. The type of the node. Possible values include:
#' \code{Treaty articles}, \code{Directives}, \code{Regulations}.
#' \code{Decisions}, \code{Court of Justice judgments}, \code{Advocate general
#' opinions}, \code{General Court judgments}, \code{National implementing
#' measures}, and \code{National court decisions}.}
#' \item{author}{String. The author of the document. If there are multiple
#' authors, they are listed, separated by a comma.}
#' \item{date}{Date. The date of the document in a \code{YYYY-MM-DD} format.
#' Coded \code{NA} for national implementing measures.}
#' \item{year}{Numeric. The year of the document. Coded \code{NA} for national
#' implementing measures.}
#' \item{month}{Numeric. The month of the document. Coded \code{NA} for
#' national implementing measures.}
#' \item{day}{Numeric. The day of the document. Coded \code{NA} for national
#' implementing measures.}
#' }
"nodes"

################################################################################
# end R script
################################################################################

